#!/bin/bash

#$ -S /bin/bash
#$ -P chicas
#$ -q gpu
#$ -l ngpus=1
# -l ncpus=2
#$ -l h_vmem=32G
#$ -l h_rt=12:00:00
#$ -j y
#$ -cwd

. /etc/profile
. $HOME/.bash_profile

module add cuda/11.0

export XLA_FLAGS="--xla_gpu_cuda_data_dir=$CUDA_HOME"

echo Args: "$@"

echo -n "Preparing config..."
CONFIG=`poetry run python -m covid.tasks.prepare_config "$@"`
echo "Done"

echo Using config: $CONFIG
echo Working directory: `pwd`

echo -n "Run inference..."
poetry run python -m covid.tasks.inference -c "$CONFIG"
echo "Done"

echo -n "Create summary..."
poetry run python -m covid.tasks.summary -c "$CONFIG"
echo "Done"

echo -n "Localisation summary..."
poetry run python -m covid.tasks.within_between -c "$CONFIG"
echo "Done"

echo -n "Hotspot detection..."
poetry run python -m covid.tasks.hotspot_detection -c "$CONFIG"
echo "Done"
