#!/bin/bash

#$ -clear
#$ -jsv /usr/shared_apps/packages/sge-8.1.9-gpu/default/common/sge_request.jsv.2.0b
#$ -S /bin/bash
#$ -P chicas
#$ -q gpu
#$ -l ngpus=1
# -l ncpus=4
#$ -l h_vmem=64G
#$ -l h_rt=12:00:00
#$ -j y
#$ -cwd

. /etc/profile
. $HOME/.bash_profile

module add cuda/11.0

export XLA_FLAGS="--xla_gpu_cuda_data_dir=$CUDA_HOME"

echo Args: "$@"

poetry run python -m covid.pipeline "$@"
