# Covid stochastic model configuration

Global:
  prependID: False
  prependDate: False
  inference_period:
    - 2020-10-11
    - 2021-01-04
  time_step: 1.


GenerateOutput:
  storeInputs: False
  scrapedDataDir: scraped_data
  storeProcessedInputs: False


data:
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume: data/201231_OFF_SEN_COVID19_road_traffic_national_table.xlsx
  reported_cases: data/Anonymised Combined Line List 20201231.csv
  case_date_type: specimen
  pillar: both
  geopackage: data/UK2019mod_pop.gpkg


mcmc:
  dmax: 84
  nmax: 50
  m: 1
  occult_nmax: 15
  num_event_time_updates: 35
  num_bursts: 200
  num_burst_samples: 50
  thin: 20
  prior:
    gamma:
      concentration: 2.0
      rate: 4.0


output:
  results_dir: output/testing
  posterior: posterior.hd5
  national_rt: national_rt.xlsx
  geopackage: prediction.gpkg
  posterior_predictive: posterior_predictive.pkl

AreaCodeData:
  input: json
  address:  "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LAD_APR_2019_UK_NC/FeatureServer/0/query?where=1%3D1&outFields=LAD19CD,LAD19NM&returnGeometry=false&returnDistinctValues=true&orderByFields=LAD19CD&outSR=4326&f=json"
  format: ons
  output: processed_data/processed_lad19cd.csv
  regions: ["E"]


TierData:
  input: api
  address: None
  format: api
