# Covid stochastic model configuration

ProcessData:
  date_range:
    - 2020-10-11
    - 2021-01-04
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume: data/201231_OFF_SEN_COVID19_road_traffic_national_table.xlsx
  reported_cases: data/Anonymised Combined Line List 20201231.csv
  case_date_type: specimen
  pillar: both

  AreaCodeData:
    input: json
    address:  "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LAD_APR_2019_UK_NC/FeatureServer/0/query?where=1%3D1&outFields=LAD19CD,LAD19NM&returnGeometry=false&returnDistinctValues=true&orderByFields=LAD19CD&outSR=4326&f=json"
    format: ons
    regions: ["E"]

  TierData:
    input: api
    address: None # Rip from gov.uk
    format: api

Mcmc:
  dmax: 84
  nmax: 50
  m: 1
  occult_nmax: 15
  num_event_time_updates: 35
  num_bursts: 1
  num_burst_samples: 100
  thin: 1

Geopackage:
  base_geopackage: data/UK2019mod_pop.gpkg

NextGenerationMatrix:
  output_file: next_generation_matrix.pkl
